# Generated by Django 6.0.1 on 2026-01-27 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_category_options_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='in_sold',
            new_name='is_sold',
        ),
    ]
